buildscript {
  ext.versions = [
    compileSdk: 36,
    kotlin: '2.3.20',
    composeUi: '1.10.6'
  ]

  repositories {
    google()
    mavenCentral()
  }

  dependencies {
    classpath "com.android.tools.build:gradle:8.13.2"
    classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$versions.kotlin"
    classpath "org.jetbrains.kotlin:compose-compiler-gradle-plugin:$versions.kotlin"
    classpath "com.vanniktech:gradle-maven-publish-plugin:0.36.0"
    classpath "org.jetbrains.dokka:dokka-gradle-plugin:2.2.0"
    classpath "app.cash.paparazzi:paparazzi-gradle-plugin:2.0.0-alpha02"
  }
}

allprojects {
  repositories {
    google()
    mavenCentral()
  }
}
